name: Teste Action React
on: [push]
jobs:
  Explore-Actions:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - run: echo "A job começou a rodar agora"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm start
      - run: echo "Acima tenho as pastas e arquivos do meu diretorio"
  
